@api = http://localhost:5000

//--------------------------------------------------------
POST {{api}}/register
Content-Type: application/json

{
    "username": "admin",
    "password": "F1tprotr@cker!"
}

###
POST {{api}}/register
Content-Type: application/json

{
    "username": "Test2",
    "password": "Test1234@"
}

//--------------------------------------------------------
###
POST {{api}}/authenticate
Content-Type: application/json

{
    "username": "admin",
    "password": "F1tprotr@cker!"
}
###
POST {{api}}/authenticate
Content-Type: application/json

{
    "username": "Test2",
    "password": "Test1234@"
}
###
GET {{api}}/users 
